In [1]:
import tensorflow as tf

In [2]:
print (tf.__version__)

1.10.0


In [3]:
hello = tf.constant ("Hello")

In [4]:
world = tf.constant ("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [9]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [10]:
print(result)

b'HelloWorld'


In [12]:
a = tf.constant(10)

In [13]:
b = tf.constant(20)

In [14]:
a+b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [15]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [16]:
a+b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [17]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [18]:
print(result)

30


In [19]:
const = tf.constant(10)

In [20]:
fill_mat = tf.fill((4,4),10)

In [21]:
myzeros=tf.zeros((4,4))

In [22]:
myones=tf.ones((4,4))

In [23]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [25]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [26]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu ]

In [27]:
sess = tf.InteractiveSession()

In [28]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[0.91780114 0.29909468 0.1297605  0.10390091]
 [0.7877406  0.05523002 0.08785379 0.6794354 ]
 [0.5723734  0.44091463 0.18616688 0.40189338]
 [0.45309913 0.92145014 0.26106668 0.5475452 ]]


[[0.58212745 0.04667819 0.5827023  0.74154174]
 [0.3337469  0.6313752  0.9153532  0.2995628 ]
 [0.5360757  0.17207623 0.84842885 0.4010762 ]
 [0.47923636 0.804291   0.7471051  0.40049994]]




In [29]:
a=tf.constant([[1,2],[3,4]])

In [30]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [31]:
b=tf.constant([[10],[100]])

In [32]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [33]:
result=tf.matmul(a,b)

In [34]:
sess.run(result)

array([[210],
       [430]])

In [35]:
result.eval()

array([[210],
       [430]])